approx:
		gcc approximate_counter.c -o approximate_counter
		./approximate_counter 4 1024 10
		rm approximate_counter

performance:
		gcc performance.c -o performance
		./performance 4 1024
		rm performance