import pandas as pd
import matplotlib.pyplot as plt

data1 = pd.read_csv("data1.csv")
data2 = pd.read_csv("data2.csv")
data3 = pd.read_csv("data3.csv")

plt.subplot(1 , 3, 1)
plt.title('No Locality Workload')
plt.xlabel('Cache Size')
plt.ylabel('Hit Rate')
plt.plot(data1['x'] , data1['y1'] , label='Optimal Policy')
plt.plot(data1['x'] , data1['y2'] , marker='x' , label='Random Policy')
plt.plot(data1['x'] , data1['y3'] , marker='.' , label='Fifo Policy')
plt.plot(data1['x'] , data1['y4'] , marker='|' , label='LRU Policy')
plt.plot(data1['x'] , data1['y5'] , marker='+' , label='Approx LRU (Clock)')
plt.legend()
plt.grid()

plt.subplot(1 , 3, 2)
plt.title('80_20 Workload')
plt.xlabel('Cache Size')
plt.ylabel('Hit Rate')
plt.plot(data2['x'] , data2['y1'] , label='Optimal Policy')
plt.plot(data2['x'] , data2['y2'] , marker='x' , label='Random Policy')
plt.plot(data2['x'] , data2['y3'] , marker='.' , label='Fifo Policy')
plt.plot(data2['x'] , data2['y4'] , marker='|' , label='LRU Policy')
plt.plot(data2['x'] , data2['y5'] , marker='+' , label='Approx LRU (Clock)')
plt.legend()
plt.grid()

plt.subplot(1 , 3, 3)
plt.title('Looping Sequential Workload')
plt.xlabel('Cache Size')
plt.ylabel('Hit Rate')
plt.plot(data3['x'] , data3['y1'] , label='Optimal Policy')
plt.plot(data3['x'] , data3['y2'] , marker='x' , label='Random Policy')
plt.plot(data3['x'] , data3['y3'] , marker='.' , label='Fifo Policy')
plt.plot(data3['x'] , data3['y4'] , marker='|' , label='LRU Policy')
plt.plot(data3['x'] , data3['y5'] , marker='+' , label='Approx LRU (Clock)')
plt.legend()
plt.grid()

plt.show()